version: '3.3'

networks:
 dfnet:
   external:
      name: default_newwork

services:
  php-fpm7:
      build: ./docker/php7/
      container_name: php-fpm7
      hostname: php-fpm7
      environment:
        TZ: Asia/Shanghai
      networks:
        dfnet:
          ipv4_address: ${PHP7_IP}
      volumes:
        - ${SOURCE_DIR}:/var/www/html:rw
        - ${PHP7_ETC_FILE}:/usr/local/etc:rw
        - ${PHP7_LOG_DIR}:/var/log/php:rw
      dns:
        - ${DNS1}
        - ${DNS2}
      restart: always
      command: php-fpm
      
  nginx:
      image: nginx:${NGINX_VERSION}
      ports:
        - "${NGINX_PORT}:80"
      container_name: nginx
      hostname: nginx
      environment:
        TZ: Asia/Shanghai
      networks:
        dfnet:
          ipv4_address: ${NGINX_IP}
      volumes:
        - ${SOURCE_DIR}:/var/www/html:rw
        - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d:rw
        - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:rw
        - ${NGINX_LOG_DIR}:/var/log/nginx:rw
      dns:
        - ${DNS1}
        - ${DNS2}
      restart: always
      command: nginx -g 'daemon off;'

  mysql:
      image: mysql:${MYSQL_VERSION}
      command: --default-authentication-plugin=mysql_native_password
      ports:
       - "${MYSQL_PORT}:3306"
      container_name: mysql
      hostname: mysql
      networks:
        dfnet:
          ipv4_address: ${MYSQL_IP}
      volumes:
        - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
        - ${MYSQL_CONF_DIR}:/etc/mysql/conf.d:rw
      dns:
        - ${DNS1}
        - ${DNS2}
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        TZ: Asia/Shanghai
      restart: always
      command: "--character-set-server=utf8mb4"

  redis-server:
      build: ./docker/redis/
      ports:
        - "${REDIS_PORT}:6379"
      container_name: redis-server
      hostname: redis-server
      environment:
        TZ: Asia/Shanghai
      networks:
        dfnet:
          ipv4_address: ${REDIS_IP}
      volumes:
        - ${REDIS_CONF_FILE}:/etc/redis.conf:rw
        - ${REDIS_LOG_DIR}:/var/log/redis/:rw
      dns:
        - ${DNS1}
        - ${DNS2}
      restart: always
      
  phpredisadmin:
      image: erikdubbelboer/phpredisadmin:${REDISMYADMIN_VERSION}
      ports:
        - "${REDISMYADMIN_PORT}:80"
      container_name: phpredisadmin
      hostname: phpredisadmin
      environment:
        - REDIS_1_HOST=redis-server
        - REDIS_1_PORT=6379
        - REDIS_1_NAME=redis-server
        - REDIS_1_AUTH=dairh
        - ADMIN_USER=admin
        - ADMIN_PASS=123456
      dns:
        - ${DNS1}
        - ${DNS2}
      networks:
        dfnet:
          ipv4_address: ${REDISMYADMIN_IP}
      restart: always
        
  mongo:
      image: mongo:${MONGO_VERSION}
      container_name: mongo
      hostname: mongo
      networks:
        dfnet:
          ipv4_address: ${MONGO_IP}
      ports:
        - ${MONGO_PORT}:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        TZ: Asia/Shanghai
      dns:
        - ${DNS1}
        - ${DNS2}
      restart: always

  mongo_express:
      image: mongo-express:${MONGO_EXPRESS_VERSION}
      container_name: mongo_express
      hostname: mongo_express
      links:
        - mongo
      networks:
        dfnet:
          ipv4_address: ${MONGO_EXPRESS_IP}
      ports:
        - ${MONGO_EXPRESS_PORT}:8081
      environment:
        ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_BASICAUTH_USERNAME}
        ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_BASICAUTH_PASSWORD}
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_MONGODB_ADMINUSERNAME}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_MONGODB_ADMINPASSWORD}
        TZ: Asia/Shanghai
      dns:
        - ${DNS1}
        - ${DNS2}
      restart: always
      
  cadvisor:
      image: registry.cn-hangzhou.aliyuncs.com/kennylee/cadvisor:apline
      container_name: cadvisor
      hostname: cadvisor
      environment:
          TZ: Asia/Shanghai
      networks:
        dfnet:
          ipv4_address: ${CADVISOR_IP}
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /cgroup:/cgroup:ro
      dns:
        - ${DNS1}
        - ${DNS2}
      ports:
        - ${CADVISOR_PORT}:8080
      logging:
        driver: 'json-file'
        options:
          max-size: '30m'
          max-file: '1'
      restart: always